// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'deck_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'deck_model.g.dart';

@Freezed()
class DeckModel with _$DeckModel {
  const factory DeckModel({
    required String deckCode,
    required Map<String, int> cardsInDeck,
  }) = _DeckModel;

  factory DeckModel.fromJson(Map<String, Object?> json) => _$DeckModelFromJson(json);
}
