// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'card_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'card_model.g.dart';

enum CardType {
  Ability,
  Landmark,
  Spell,
  Trap,
  Unit,
}

enum Region {
  @JsonValue('Bandle City')
  BandleCity,
  Bilgewater,
  Demacia,
  Freljord,
  Ionia,
  Noxus,
  @JsonValue('Piltover & Zaun')
  PiltoverAndZaun,
  Runeterra,
  @JsonValue('Shadow Isles')
  ShadowIsles,
  Shurima,
  Targon,
}

enum Keywords {
  Attach,
  Attune,
  Augment,
  Autoplay,
  Burst,
  Barrier,
  Challenger,
  Countdown,
  Deep,
  DoubleStrike,
  Elusive,
  Ephemeral,
  Fast,
  Fearsome,
  Fleeting,
  Focus,
  Formidable,
  Fury,
  Imbue,
  Immobile,
  Impact,
  Landmark,
  LandmarkVisualOnly,
  LastBreath,
  Lifesteal,
  Lurker,
  MissingTranslation,
  Overwhelm,
  QuickStrike,
  Regeneration,
  Scout,
  Skill,
  Slow,
  SpellShield,
  Support,
  Tough,
  Trap,
  Vulnerable,
  @JsonValue('AuraVisualFakeKeyword')
  None,
}

enum SpellSpeed {
  @JsonValue('')
  None,
  Burst,
  Fast,
  Slow,
}

@Freezed()
class CardModel with _$CardModel {
  const factory CardModel({
    required List<Region> regions,
    required int attack,
    required int cost,
    required int health,
    required String descriptionRaw,
    required String levelupDescriptionRaw,
    required String flavorText,
    required String artistName,
    required String name,
    required String cardCode,
    required List<Keywords> keywordRefs,
    SpellSpeed? spellSpeed,
    required CardType type,
  }) = _CardModel;

  factory CardModel.fromJson(Map<String, Object?> json) => _$CardModelFromJson(json);
}
