// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'card_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'card_model.g.dart';

enum CardType {
  Ability,
  Landmark,
  Spell,
  Trap,
  Unit,
}

enum Region {
  BandleCity,
  Bilgewater,
  Demacia,
  Freljord,
  Ionia,
  Noxus,
  PiltoverAndZaun,
  ShadowIsles,
  Shurima,
  Targon,
}

enum Keywords {
  Attach,
  Attune,
  Augment,
  Burst,
  Challenger,
  Countdown,
  DoubleAttack,
  Elusive,
  Ephemeral,
  Fast,
  Fearsome,
  Fleeting,
  Focus,
  Formidable,
  Fury,
  Imbue,
  Impact,
  Landmark,
  LastBreath,
  Lifesteal,
  MissingTranslation,
  Overwhelm,
  QuickAttack,
  Regeneration,
  Scout,
  Skill,
  Slow,
  SpellShield,
  Tough,
  Trap,
}

enum SpellSpeed {
  Burst,
  Fast,
  Slow,
}

@freezed
class CardModel with _$CardModel {
  const factory CardModel({
    required List<Region> regions,
    required int attack,
    required int cost,
    required int health,
    required String descriptionRaw,
    required String levelupDescriptionRaw,
    required String flavorText,
    required String artistName,
    required String cardName,
    required String cardCode,
    required List<Keywords> keywords,
    required SpellSpeed spellSpeed,
    required CardType cardType,
  }) = _CardModel;

  factory CardModel.fromJson(Map<String, Object?> json) => _$CardModelFromJson(json);
}
