import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';
import 'package:riot_api/riot_api.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'runeterra_card.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.

@Freezed()
class RuneterraCard with _$RuneterraCard {
  const factory RuneterraCard({
    required CardModel cardDetails,
    required int amount,
  }) = _RuneterraCard;
}
