// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'game_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'game_model.g.dart';

@Freezed()
class GameModel with _$GameModel {
  @JsonSerializable(fieldRename: FieldRename.pascal)
  const factory GameModel({
    required String? playerName,
    required String? opponentName,
    required String? gameState,
    required Map<String, int>? screen,
    required List<Map<String, dynamic>>? rectangles,
  }) = _GameModel;

  factory GameModel.fromJson(Map<String, Object?> json) => _$GameModelFromJson(json);
}
